// Regenerates the cross-workspace Tour fixture consumed by
// `packages/shared/src/fixtures/bratislava-tour.json`.
//
// That fixture exists so apps/web's TriggerEngine tests can drive a REAL
// assembled Tour — proving the pipeline's actual output is playable —
// without apps/web importing apps/api directly (a cross-app-workspace
// dependency the project avoids; see task-8-report.md). Both apps already
// depend on @ai-guide/shared, so a static fixture living there is the
// seam: this script is the only place that computes it, from the same
// synthetic/recorded inputs `assemble.test.ts` uses, and `assemble.test.ts`
// asserts `assembleTour(...)` still reproduces it byte-for-byte — so the
// fixture cannot silently drift from what assembleTour actually produces.
//
// Never calls the Anthropic API — the narration used here is the
// hand-authored synthetic cassette, and the route is replayed from the
// already-recorded Mapbox cassette. Run from the repo root:
//
//   node --experimental-strip-types apps/api/scripts/generate-tour-fixture.ts
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CuratedStop, NarrationOutput, Tour } from '@ai-guide/shared';
import { FileCassetteStore } from '../src/cassette/index.ts';
import { createRedactingCassetteFetch } from '../src/stages/routing/mapbox.ts';
import { route } from '../src/stages/routing/index.ts';
import { assembleTour } from '../src/stages/narration/assemble.ts';

const here = dirname(fileURLToPath(import.meta.url));
const cassetteDir = join(here, '..', 'cassettes');
const fixturePath = join(here, '..', '..', '..', 'packages', 'shared', 'src', 'fixtures', 'bratislava-tour.json');

async function main(): Promise<void> {
  const curationRaw = await readFile(join(cassetteDir, 'synthetic', 'curation-bratislava.json'), 'utf8');
  const curationCassette = JSON.parse(curationRaw) as { tourTitle: string; stops: CuratedStop[] };

  const narrationRaw = await readFile(join(cassetteDir, 'synthetic', 'narration-bratislava-sk.json'), 'utf8');
  const narrationCassette = JSON.parse(narrationRaw) as NarrationOutput;

  const store = new FileCassetteStore(cassetteDir);
  const unusedLive: typeof fetch = async () => {
    throw new Error('replay must never call through to a live fetch');
  };
  const fetchImpl = createRedactingCassetteFetch('replay', store, unusedLive);

  const routeResult = await route(curationCassette.stops, 90, { fetch: fetchImpl, token: 'unused-in-replay' });

  const tour: Tour = assembleTour({
    tourId: 'bratislava-castle-to-old-town-sk',
    tourTitle: curationCassette.tourTitle,
    city: 'Bratislava',
    request: {
      city: 'Bratislava',
      profileText: 'brutalist architecture, and I hate crowds',
      language: 'sk',
      persona: 'a grumpy local historian',
      budgetMin: 90,
    },
    stops: curationCassette.stops,
    route: routeResult,
    narration: { segments: narrationCassette.segments },
  });

  const fixture = {
    _generated: true,
    _comment:
      'Generated by apps/api/scripts/generate-tour-fixture.ts from the recorded Bratislava routing cassette and the hand-authored synthetic curation/narration cassettes. Do not hand-edit — regenerate with that script. apps/api/src/stages/narration/assemble.test.ts asserts assembleTour(...) still reproduces this fixture exactly. Consumed by apps/web/src/lib/trigger/assembledTour.test.ts to drive the real TriggerEngine end to end.',
    tour,
  };

  await writeFile(fixturePath, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
  console.log(`Wrote ${tour.segments.length}-segment Tour fixture to ${fixturePath}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exitCode = 1;
});
